version: 2.1

references:
  defaults: &defaults
    working_directory: ~/addons-contribution-notifier
    docker:
      - image: cimg/node:16.14

  restore_build_cache: &restore_build_cache
    restore_cache:
      name: restore npm package cache
      keys:
        - npm-packages-{{ checksum "package-lock.json" }}

  run_npm_install: &run_npm_install
    run:
      name: install dependencies
      command: npm install

  save_build_cache: &save_build_cache
    save_cache:
      name: save npm package cache
      key: npm-packages-{{ checksum "package-lock.json" }}
      paths:
        - ./node_modules

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_build_cache
      - *run_npm_install
      - *save_build_cache
      - run: npm run test-ci

workflows:
  version: 2
  default-workflow:
    jobs:
      - test
